# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ba282c3abec4ff38a2831f4f86daf157d8690f2cbdc8ec1327aaf4160097a413026b6ab8f812e91695c757a3b2c9481726de5a475d1ce7641052ef26d7a7157

test:
  secret_key_base: 70179462e2d73c4cffbac5fbe266ef191b3a03f1b921e24be491cd81848fcf5037f8e68c278c1a5827fda2e201536ef013aedc7572dbae914ffaa389f7e48bfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
